### ISSUE TITLE
[Tracking] Create Optimal Synthetic Workloads / "Kernel Event Rates" for Falco Testing 

### ISSUE THREAD

**Issue by incertum** [falcosecurity/cncf-green-review-testing#11]
Creating a formal issue on our side to formally track the progress we are making wrt to tuning the synthetic workloads in relation to the CNCF testbed constraints, so that the reported Falco Metrics are as realistic as possible.

@AntonioDiTuri @nikimanoledaki @rossf7

**Comment by incertum** [comment]
@AntonioDiTuri re https://github.com/cncf-tags/green-reviews-tooling/issues/43#issuecomment-1930332605:

Correct it's all setup as outlined in https://falco.org/docs/metrics/falco-metrics/
Our `falco.yaml` is a configMap, see [here](https://github.com/falcosecurity/cncf-green-review-testing/blob/9f763dc409c615cffaa2e4e7ff297338ad9069c6/kustomize/falco-driver/modern_ebpf/configmap.yaml#L82-L92).

I am looking at the following metrics:

```yaml
falco.cpu_usage_perc
falco.cpu_usage_perc_total_host
falco.host_num_cpus
scap.evts_rate_sec
```

On that note: I anticipated much larger machines (e.g. 64, 96 CPUs, not only 16 CPUs) -> hence I believe I am currently stressing the machine out way too much (!!!!!) - we are at a less realistic / very high load for an average server load use case. Right now we are at 102K events / second when normalized for one CPU. We should be targeting something like 1-3K per one CPU, for example read this new guide: https://falco.org/docs/troubleshooting/dropping/

Allow some time for me to experiment now that I have access to the falco pods. meanwhile, happy to answer more follow up questions.

**Comment by AntonioDiTuri** [comment]
Are those metrics that are saved in the /tmp/stats folder also accessible via REST API?

**Comment by incertum** [comment]
> Are those metrics that are saved in the /tmp/stats folder also accessible via REST API?

No, `kubectl cp` could be an interim solution. However, since we are targeting Prometheus support by Falco 0.38.0 (the next release) I would propose to skip workarounds (https://github.com/falcosecurity/cncf-green-review-testing/issues/12). Meanwhile we can ad-hoc inspect these JSONL metrics outputs we have today. In a way, they are helper metrics (nice-to-haves) in order to configure Falco optimally for best benchmarking results.

> [We are interested in building a Grafana dashboard that could graph those metrics](https://github.com/cncf-tags/green-reviews-tooling/issues/46)

Absolutely, let's discuss then.

> One more question: can we use the [Falco Prometheus exporter](https://github.com/falcosecurity/falco-exporter) to have those metrics available for the Grafana Dashboard?

This comment answers your question https://github.com/falcosecurity/cncf-green-review-testing/issues/12#issue-2122460300. No we can not, plus the Falco maintainers have decided to deprecate that https://github.com/falcosecurity/falco-exporter all together.

**Comment by AntonioDiTuri** [comment]
@incertum when do you plan to release Falco 0.38.0? Is there a file I can check in the falco for planned releases and related updates?

**Comment by incertum** [comment]
@AntonioDiTuri absolutely, we link to our roadmap [here](https://github.com/falcosecurity/falco?tab=readme-ov-file#whats-next-for-falco) and our Falco 0.38.0 milestone is currently set to May 27, 2024, see [here](https://github.com/falcosecurity/falco/milestone/37). 

Please follow this issue https://github.com/falcosecurity/cncf-green-review-testing/issues/12 to track our Prometheus integration progress. Thanks for your patience.
